version: '3'
services:
  api:
    build: ./
    container_name: github_link_creator
    ports:
      - "8080:8080"
    environment:
      API_PORT: :8080
      LOG_LEVEL: ERROR
    volumes:
      - ./:/api
